application: rh-csse290-gas-stats
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /_ah/spi/.*
  script: gas_stats_api.app
  
 - url: /car/.*
   script: main.app
   
 - url: /epacar/.*
   script: epa.app
  
- url: .*
  script: main.app
  
builtins:
- datastore_admin: on

libraries:
- name: webapp2
  version: "2.5.2"
- name: endpoints
  version: latest
- name: jinja2
  version: latest