/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLGasstatsGasStat.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   gasstats/v1
// Description:
//   GasStats API
// Classes:
//   GTLGasstatsGasStat (0 custom class methods, 8 custom properties)

#import "GTLGasstatsGasStat.h"

// ----------------------------------------------------------------------------
//
//   GTLGasstatsGasStat
//

@implementation GTLGasstatsGasStat
@dynamic carId, cost, createDateTime, entityKey, gallons, miles, mpg, userId;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      @"car_id", @"carId",
      @"create_date_time", @"createDateTime",
      @"user_id", @"userId",
      nil];
  return map;
}

@end
