/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLGasstatsEpaCar.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   gasstats/v1
// Description:
//   GasStats API
// Classes:
//   GTLGasstatsEpaCar (0 custom class methods, 7 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLGasstatsEpaCar
//

@interface GTLGasstatsEpaCar : GTLObject
@property (retain) NSNumber *cityMpg;  // doubleValue
@property (retain) NSNumber *combMpg;  // doubleValue
@property (copy) NSString *entityKey;
@property (retain) NSNumber *highMpg;  // doubleValue
@property (copy) NSString *make;
@property (copy) NSString *model;
@property (retain) NSNumber *year;  // longLongValue
@end
