/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLGasstatsGasStatCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   gasstats/v1
// Description:
//   GasStats API
// Classes:
//   GTLGasstatsGasStatCollection (0 custom class methods, 2 custom properties)

#import "GTLGasstatsGasStatCollection.h"

#import "GTLGasstatsGasStat.h"

// ----------------------------------------------------------------------------
//
//   GTLGasstatsGasStatCollection
//

@implementation GTLGasstatsGasStatCollection
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLGasstatsGasStat class]
                                forKey:@"items"];
  return map;
}

@end
