/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLGasstatsEpaCarCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   gasstats/v1
// Description:
//   GasStats API
// Classes:
//   GTLGasstatsEpaCarCollection (0 custom class methods, 2 custom properties)

#import "GTLGasstatsEpaCarCollection.h"

#import "GTLGasstatsEpaCar.h"

// ----------------------------------------------------------------------------
//
//   GTLGasstatsEpaCarCollection
//

@implementation GTLGasstatsEpaCarCollection
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLGasstatsEpaCar class]
                                forKey:@"items"];
  return map;
}

@end
