/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLGasstatsGasStat.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   gasstats/v1
// Description:
//   GasStats API
// Classes:
//   GTLGasstatsGasStat (0 custom class methods, 8 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLGasstatsGasStat
//

@interface GTLGasstatsGasStat : GTLObject
@property (retain) NSNumber *carId;  // longLongValue
@property (retain) NSNumber *cost;  // doubleValue
@property (copy) NSString *createDateTime;
@property (copy) NSString *entityKey;
@property (retain) NSNumber *gallons;  // doubleValue
@property (retain) NSNumber *miles;  // doubleValue
@property (retain) NSNumber *mpg;  // doubleValue
@property (retain) NSNumber *userId;  // longLongValue
@end
