/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLGasstatsEpaCar.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   gasstats/v1
// Description:
//   GasStats API
// Classes:
//   GTLGasstatsEpaCar (0 custom class methods, 7 custom properties)

#import "GTLGasstatsEpaCar.h"

// ----------------------------------------------------------------------------
//
//   GTLGasstatsEpaCar
//

@implementation GTLGasstatsEpaCar
@dynamic cityMpg, combMpg, entityKey, highMpg, make, model, year;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      @"city_mpg", @"cityMpg",
      @"comb_mpg", @"combMpg",
      @"high_mpg", @"highMpg",
      nil];
  return map;
}

@end
