/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLGasstatsDriver.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   gasstats/v1
// Description:
//   GasStats API
// Classes:
//   GTLGasstatsDriver (0 custom class methods, 6 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLGasstatsDriver
//

@interface GTLGasstatsDriver : GTLObject
@property (copy) NSString *createDateTime;
@property (copy) NSString *email;
@property (copy) NSString *entityKey;
@property (copy) NSString *password;
@property (retain) NSNumber *userId;  // longLongValue
@property (copy) NSString *username;
@end
