/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLGasstats.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   gasstats/v1
// Description:
//   GasStats API

#import "GTLGasstatsConstants.h"

#import "GTLGasstatsCar.h"
#import "GTLGasstatsCarCollection.h"
#import "GTLGasstatsDriver.h"
#import "GTLGasstatsDriverCollection.h"
#import "GTLGasstatsEpaCar.h"
#import "GTLGasstatsEpaCarCollection.h"
#import "GTLGasstatsGasStat.h"
#import "GTLGasstatsGasStatCollection.h"
#import "GTLGasstatsTankRecord.h"
#import "GTLGasstatsTankRecordCollection.h"

#import "GTLQueryGasstats.h"
#import "GTLServiceGasstats.h"
