/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLGasstatsCar.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   gasstats/v1
// Description:
//   GasStats API
// Classes:
//   GTLGasstatsCar (0 custom class methods, 9 custom properties)

#import "GTLGasstatsCar.h"

// ----------------------------------------------------------------------------
//
//   GTLGasstatsCar
//

@implementation GTLGasstatsCar
@dynamic carId, createDateTime, entityKey, icon, make, model, shared, userId,
         year;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      @"car_id", @"carId",
      @"create_date_time", @"createDateTime",
      @"user_id", @"userId",
      nil];
  return map;
}

@end
