/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLGasstatsTankRecord.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   gasstats/v1
// Description:
//   GasStats API
// Classes:
//   GTLGasstatsTankRecord (0 custom class methods, 6 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLGasstatsTankRecord
//

@interface GTLGasstatsTankRecord : GTLObject
@property (retain) NSNumber *avgTank;  // doubleValue
@property (retain) NSNumber *bestTank;  // doubleValue
@property (retain) NSNumber *carId;  // longLongValue
@property (copy) NSString *entityKey;
@property (retain) NSNumber *lastTank;  // doubleValue
@property (retain) NSNumber *userId;  // longLongValue
@end
