/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLGasstatsCarCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   gasstats/v1
// Description:
//   GasStats API
// Classes:
//   GTLGasstatsCarCollection (0 custom class methods, 2 custom properties)

#import "GTLGasstatsCarCollection.h"

#import "GTLGasstatsCar.h"

// ----------------------------------------------------------------------------
//
//   GTLGasstatsCarCollection
//

@implementation GTLGasstatsCarCollection
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLGasstatsCar class]
                                forKey:@"items"];
  return map;
}

@end
