/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLGasstatsTankRecordCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   gasstats/v1
// Description:
//   GasStats API
// Classes:
//   GTLGasstatsTankRecordCollection (0 custom class methods, 2 custom properties)

#import "GTLGasstatsTankRecordCollection.h"

#import "GTLGasstatsTankRecord.h"

// ----------------------------------------------------------------------------
//
//   GTLGasstatsTankRecordCollection
//

@implementation GTLGasstatsTankRecordCollection
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLGasstatsTankRecord class]
                                forKey:@"items"];
  return map;
}

@end
