/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLGasstatsConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   gasstats/v1
// Description:
//   GasStats API

#import "GTLGasstatsConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeGasstatsUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
